#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint-staged ||
(
    echo "[🧿 ESLint]: ESLint check failed 😤😤
    Make the required changes listed above, add changes and try to commit again."
    false;
)

echo '✅✅ You win this time... I am committing this now. ✅✅'
